### PR TITLE
Kavi frontend changes: Login page and Landing page

### PR DESCRIPTION
**Pull request by iyerkaveri**
Basic frontend done for login page and landing page.
Added:
- UniversalStyle.tsx in components for exportable styles in use throughout the app
- design changes to login page (app/index.tsx) as well as landing page (app/auth/index.tsx)
- 2 images to assets/images for background rendering on login page

### CODE REVIEW

**Comment by SunhuChoi** [comment]
LGTM!

**Review by SunhuChoi — COMMENTED** [review]
LGTM!

**Review by SunhuChoi — APPROVED** [review]

**Review by hongye-liang — APPROVED** [review]
LGTM! Well done!

**Comment by Helen123** [comment]
LGTM!

**Pull request merged**
