### PR TITLE
Fixing android uri issue

### LINKED ISSUE #82: Fixing Android compatibility issues with inserting URI

### PR DESCRIPTION
**Pull request by SunhuChoi**
## EDIT: Good to merge now!

Fixed URI decoding error for android where it gets incorrectly converted when sent from add-recipe.tsx to Next.tsx. A full explanation is in the #pr-reviews-and-documentation channel.

Closes #82

### CODE REVIEW

**Review by chauAlex — CHANGES_REQUESTED** [review]
Looks good -- but take out the image picker permission if it's not necessary (in app.json).

**Review by chauAlex — APPROVED** [review]
LGTM!

**Review by rainakakani21 — APPROVED** [review]
lgtm

**Review by Helen123 — COMMENTED** [review]
LGTM

**Pull request merged**
