### PR TITLE
Added documentation for 10/9

### PR DESCRIPTION
**Pull request by iyerkaveri**
today's lecture documentation as well as README added.

### CODE REVIEW

**Comment by anushkavijay** [comment]
LGTM :)

**Comment by SunhuChoi** [comment]
LGTM!

**Comment by hongye-liang** [comment]
LGTM

**Comment by chauAlex** [comment]
Looks G to M

**Comment by Helen123** [comment]
LGTM :)

**Review by chauAlex — APPROVED** [review]
LGTM!

**Review by rainakakani21 — APPROVED** [review]
LGTM

**Review by anushkavijay — COMMENTED** [review]
LGTM :)

**Review by Helen123 — COMMENTED** [review]
LGTM :)

**Review by Helen123 — APPROVED** [review]

**Review by SunhuChoi — APPROVED** [review]

**Review by hongye-liang — APPROVED** [review]
LGTM!

**Pull request merged**
