### PR TITLE
Added searching functionality, with dummy invite button

### LINKED ISSUE #32: Search for Friends
- [ ] Search bar to search for friends by username
- [ ] Upon entering a username, you see a name and button to invite, otherwise it says not found

### PR DESCRIPTION
**Pull request by chauAlex**
Added searching functionality, with dummy invite button

Closes #32

### CODE REVIEW

**Review by iyerkaveri — APPROVED** [review]
LGTM

**Review by Helen123 — APPROVED** [review]
LGTM

**Review by SunhuChoi — APPROVED** [review]
This is goated!

**Review by hongye-liang — APPROVED** [review]
LGTM, well done!

**Pull request merged**
